// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **



'use strict';

function main() {
  const parent = 'projects/bigquery-demo-387504'
  const transferConfig = {
    displayName: "s3-transfer-01",
    dataSourceId: "amazon_s3",
    destinationDatasetId: "bigquery-demo-387504.s3_data",   // dest dataset name
    scheduleOptions: {
        disableAutoScheduling: true
    },
  }

  // Imports the Datatransfer library
  const {DataTransferServiceClient} = require('@google-cloud/bigquery-data-transfer').v1;

  // Instantiates a client
  const datatransferClient = new DataTransferServiceClient();

  async function callCreateTransferConfig() {
    // Construct request
    const request = {
      parent,
      transferConfig,
    };

    // Run request
    const response = await datatransferClient.createTransferConfig(request);
    console.log(response);
  }

  callCreateTransferConfig();
}

process.on('unhandledRejection', err => {
  console.error(err.message);
  process.exitCode = 1;
});
main();